-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.avion
(
    id_avion integer NOT NULL,
    id_modelo integer NOT NULL,
    id_compania integer NOT NULL,
    capacidad integer NOT NULL,
    CONSTRAINT avion_pkey PRIMARY KEY (id_avion)
);

CREATE TABLE IF NOT EXISTS public.clase
(
    id_clase integer NOT NULL,
    nombre character varying(30) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT clase_pkey PRIMARY KEY (id_clase)
);

CREATE TABLE IF NOT EXISTS public.cliente
(
    id_cliente integer NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    dni character varying(30) COLLATE pg_catalog."default" NOT NULL,
    id_pais integer NOT NULL,
    CONSTRAINT cliente_pkey PRIMARY KEY (id_cliente)
);

CREATE TABLE IF NOT EXISTS public.compania
(
    id_compania integer NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT compania_pkey PRIMARY KEY (id_compania)
);

CREATE TABLE IF NOT EXISTS public.compra
(
    monto numeric NOT NULL,
    fecha date NOT NULL,
    id_compra integer NOT NULL,
    id_cliente integer NOT NULL,
    id_pasaje integer NOT NULL,
    CONSTRAINT compra_pkey PRIMARY KEY (id_compra)
);

CREATE TABLE IF NOT EXISTS public.empleado
(
    id_empleado integer NOT NULL,
    dni character varying(30) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(80) COLLATE pg_catalog."default" NOT NULL,
    sueldo numeric NOT NULL,
    id_compania integer NOT NULL,
    CONSTRAINT empleado_pkey PRIMARY KEY (id_empleado)
);

CREATE TABLE IF NOT EXISTS public.log_vuelo_empleado
(
    id_log_vuelo_empleado bigint NOT NULL DEFAULT nextval('log_vuelo_empleado_id_log_vuelo_empleado_seq'::regclass),
    id_vuelo bigint NOT NULL,
    id_empleado bigint NOT NULL,
    CONSTRAINT id_log_vuelo_empleado PRIMARY KEY (id_log_vuelo_empleado)
);

CREATE TABLE IF NOT EXISTS public.modelo
(
    id_modelo integer NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT modelo_pkey PRIMARY KEY (id_modelo)
);

CREATE TABLE IF NOT EXISTS public.pais
(
    nombre character varying(70) COLLATE pg_catalog."default" NOT NULL,
    id_pais integer NOT NULL,
    CONSTRAINT pais_pkey PRIMARY KEY (id_pais)
);

CREATE TABLE IF NOT EXISTS public.pasaje
(
    id_pasaje integer NOT NULL,
    id_clase integer NOT NULL,
    CONSTRAINT pasaje_pkey PRIMARY KEY (id_pasaje)
);

CREATE TABLE IF NOT EXISTS public.viaje
(
    id_viaje bigint NOT NULL DEFAULT nextval('viaje_id_viaje_seq'::regclass),
    id_pasaje bigint NOT NULL,
    id_vuelo bigint NOT NULL,
    CONSTRAINT vpkey_viaje PRIMARY KEY (id_viaje)
);

CREATE TABLE IF NOT EXISTS public.vuelo
(
    id_vuelo integer NOT NULL,
    embarque date NOT NULL,
    id_origen integer NOT NULL,
    id_destino integer NOT NULL,
    CONSTRAINT vuelo_pkey PRIMARY KEY (id_vuelo)
);

ALTER TABLE IF EXISTS public.avion
    ADD CONSTRAINT id_compania_fk FOREIGN KEY (id_compania)
    REFERENCES public.compania (id_compania) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.avion
    ADD CONSTRAINT id_modelo_fk FOREIGN KEY (id_modelo)
    REFERENCES public.modelo (id_modelo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.cliente
    ADD CONSTRAINT id_pais_fk FOREIGN KEY (id_pais)
    REFERENCES public.pais (id_pais) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.compra
    ADD CONSTRAINT id_cliente_fk FOREIGN KEY (id_cliente)
    REFERENCES public.cliente (id_cliente) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.compra
    ADD CONSTRAINT id_pasaje_fk FOREIGN KEY (id_pasaje)
    REFERENCES public.pasaje (id_pasaje) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.empleado
    ADD CONSTRAINT id_compania_fk FOREIGN KEY (id_compania)
    REFERENCES public.compania (id_compania) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.log_vuelo_empleado
    ADD CONSTRAINT id_empleado FOREIGN KEY (id_empleado)
    REFERENCES public.empleado (id_empleado) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.log_vuelo_empleado
    ADD CONSTRAINT id_vuelo FOREIGN KEY (id_vuelo)
    REFERENCES public.vuelo (id_vuelo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pasaje
    ADD CONSTRAINT id_clase_fk FOREIGN KEY (id_clase)
    REFERENCES public.clase (id_clase) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.viaje
    ADD CONSTRAINT id_pasaje FOREIGN KEY (id_pasaje)
    REFERENCES public.pasaje (id_pasaje) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.viaje
    ADD CONSTRAINT id_vuelo FOREIGN KEY (id_vuelo)
    REFERENCES public.vuelo (id_vuelo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.vuelo
    ADD CONSTRAINT id_destino FOREIGN KEY (id_destino)
    REFERENCES public.pais (id_pais) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.vuelo
    ADD CONSTRAINT id_origen FOREIGN KEY (id_origen)
    REFERENCES public.pais (id_pais) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;